image: node:latest

# This folder is cached between builds
# http://docs.gitlab.com/ce/ci/yaml/README.html#cache
cache:
  paths:
  - node_modules/

stages:
  - build
  - audit
  - check
  - deploy

build:
  stage: build
  tags:
    - dockerex
  script:
    - export DEMO='$DEMO'
    - npm install --no-progress
    - npm run build-silent
  artifacts:
    paths:
    - dist/
    - index.html

audit:
  stage: audit
  tags:
    - dockerex
  script: npm audit

eslint:
  stage: check
  tags:
    - dockerex
  script: npm run lint

deploy:
  stage: deploy
  tags:
    - dockerex
  image: docker:latest
  services:
    - docker:dind
  script:
    - DOCKER_TAG_NAME=$(echo $CI_COMMIT_REF_SLUG- | sed 's/^master-$//')
    - docker build --pull -t titan-ccp-frontend .
    - docker tag titan-ccp-frontend industrialdevops/titan-ccp-frontend:${DOCKER_TAG_NAME}latest
    - docker tag titan-ccp-frontend industrialdevops/titan-ccp-frontend:$DOCKER_TAG_NAME$(date +%Y%m%d%H%M%S)
    - docker tag titan-ccp-frontend industrialdevops/titan-ccp-frontend:$DOCKER_TAG_NAME$CI_COMMIT_SHA
    - echo $DOCKERHUB_PW | docker login -u $DOCKERHUB_ID --password-stdin
    - docker push industrialdevops/titan-ccp-frontend
    - docker logout
  only:
    variables:
      - $DOCKERHUB_ID
      - $DOCKERHUB_PW